proxy:
  port: 28467
client:
  hub_address: 127.0.0.1
  hub_port: 7314
  passive: true
  nick: cenphol2
  # active_port: 7315
  # search_port: 7316
  # address: 128.2.152.87
# debug: 0, info: 1, warn: 2, error: 3
logger_level: 0

