#!/usr/bin/env ruby

require 'rubygems'
require 'shout'

BLOCKSIZE = 16384

s       = Shout.new
s.host  = 'localhost'
s.port  = 8000
s.mount = '/awesome-development'
s.user  = 'source'
s.pass  = 'mightiest550@tendentiousness'
s.format = Shout::OGG

s.connect

# ARGV.each do |filename|
filename = '/Users/alex/test.ogg'
p filename
i = 0
File.open(filename) do |file|
  puts "sending data from #{filename}"
  m = ShoutMetadata.new
  m.add 'filename', filename
  s.metadata = m

  while data = file.read(BLOCKSIZE)
    p i
    i += 1
    s.send data
    s.sync
  end
end
p i
# end
sleep 100
s.disconnect
