#!/usr/bin/env ruby

require 'rubygems'
require 'daemons'

require File.dirname(__FILE__) + '/../lib/push_server'


#Daemons.run rails_root + '/lib/push_server.rb',
#            :dir => rails_root + '/tmp/pids',
#            :dir_mode => :normal
#
options = {
  :dir_mode => :normal,
  :dir => File.dirname(__FILE__) + '/../log/',
  :log_output => true,
  :backtrace => true
}

Daemons.run_proc('push_server', options) do
  PushServer.logger.info ''
  PushServer.logger.info '====== STARTING SERVER ======='
  PushServer.logger.info ''
  EventMachine::run {
    EM.epoll
    EM.start_server '127.0.0.1', '8081', PushServer
  }
end
