#!/usr/bin/env ruby

require 'pusher'
require 'fargo'
require 'resque'
require 'resque/status'
require 'eventmachine'

require File.expand_path('../../config/initializers/pusher', __FILE__)
require File.expand_path('../../app/workers/fargo_search', __FILE__)
require File.expand_path('../../app/workers/fargo_download', __FILE__)
require File.expand_path('../../app/workers/convert_song', __FILE__)

EM.run {
  client = Fargo::Client.new
  client.config.color = true
  client.connect
  FargoSearch.client = FargoDownload.client = client

  searcher = Resque::Worker.new 'search'

  # Process all pending requests
  EM.add_periodic_timer(1) do
    while job = Resque.reserve(:search)
      searcher.perform job
    end

    while job = Resque.reserve(:downloads)
      downloader = Resque::Worker.new 'downloader'
      EM.defer { downloader.perform job }
    end
  end
}
